const A380Questions = [
    { q: "🪓 State the pre-flight check of the Crash Axe.", a: "**Correct quantity** and **securely stowed** 🔢✅🔒" },
    { q: "🛝 Which A380 doors are equipped with fuselage integrated slide rafts?", a: "**All Upper Deck doors** 🚪🛶🚪🛶" },
    { q: "🚨 What does the cabin door warning system consist of?", a: "• **Slide Armed light** 💡🟡\n• **Cabin Pressure light** 💡🔴" },
    { q: "🚪 Which doors will UR2 Cabin Crew demonstrate in case of an emergency landing?", a: "**U1 & U2 doors** 1️⃣🚪2️⃣🚪" },
    { q: "🎈 During Cabin Door Emergency Operation, what should Cabin Crew do if the slide raft/escape slide has not inflated automatically?", a: "Press the <span style=\"color: red;\">**red Manual Inflation Push button (MIP)**</span> 🔴👆🛶" },
    { q: "🚫 True or False? Passengers who may hinder other passengers during an evacuation or who might impede the crew in carrying out their duties, shall not be allocated seats which permit direct access to emergency exits.", a: "**True** ✅🚷" },
    { q: "📺 When should Cabin Crew ensure the Personal Video Screens (PVS) are stowed for take-off?", a: "For take-off this should be completed when the **safety demonstration video has finished playing** 🎬➡️🔒" },
    { q: "👶 True or False? Baby bassinets can be placed on the floor during cruise.", a: "**False** ❌\nBaby bassinets must **not be placed on the floor at any time** 👶🛏️🚫" },
    { q: "🔑 Where is the upper avionics compartment door key stowed?", a: "The designated key is stowed in the **Flight Deck** 🛩️🔐" },
    { q: "🔢 State both the normal and the emergency access codes to the Flight Deck.", a: "• Normal: **1** then **#** 1️⃣#️⃣\n• Emergency: **3 4 5** and **#** 3️⃣4️⃣5️⃣#️⃣" },
    { q: "📞 How can Cabin Crew make a Priority call to the Flight Deck?", a: "Press '**PRIO**' '**CAPT**' and '**SEND**' on the handset 🔴👨‍✈️📤" },
    { q: "🔔 What is the audio indication in the cabin when an Emergency call is initiated?", a: "**3 Hi-Lo chimes** 🔔🔔🔔" },
    { q: "💨 What actions must the Cabin Crew take when a Rapid Decompression occurs?", a: "The following actions should be conducted simultaneously:\n• **Put on** the nearest drop-down oxygen mask 😷\n• **Sit down and secure yourself** 💺🔒\n• **Tilt, wedge, apply brakes and hold** the cart, when applicable 🛒🛑" },
    { q: "⏱️ What is the duration of the cabin automatic drop-down oxygen system?", a: "The duration of flow will depend on:\n• The **number of masks in use** 😷🔢\n• The **cabin altitude**, the lower the altitude the less oxygen that will flow into the masks 🏔️📉" },
    { q: "🛑 When will the cabin automatic drop-down oxygen system deactivate?", a: "When the cabin altitude reaches **10,000 feet**, the oxygen flow will stop 🏔️🚫💨" },
    { q: "🌪️ State the post turbulence management of lavatories for light turbulence.", a: "Once the seat belt sign has been switched off, Cabin Crew shall **unlock the lavatories/shower SPA** 🚽🔓🚿" },
    { q: "👶 State the procedure to be followed regarding the Infant/ Extension Seat Belts after passenger disembarkation.", a: "Cabin Crew must **collect the infant/extension seat belts** in their safety area of responsibility and **return them to the correct stowage** 👶🔙🧳" },
    { q: "🔥 How often shall Cabin Crew check for fire/smoke hazard in the galleys and lavatories?", a: "Recommended at least **every 30 minutes** ⏰3️⃣0️⃣" },
    { q: "🧯 State the procedure to be followed once the Lavatory Automatic Fire Extinguisher has discharged.", a: "The lavatory must be **locked** 🔒, **monitored** 👀 and should **not be used** for the remainder of the flight 🚫🚽" },
    { q: "🚭 True or False? Smoke curtains are designed for use on ground and in-flight.", a: "**False** ❌\nSmoke curtains are designed for use **on ground only** 🛬🚭" },
    { q: "🔦 When should the Emergency Flashlight be used?", a: "During **in-flight emergencies** and **evacuation** when the visibility is restricted due to smoke, fumes or poor light conditions 🆘🏃‍♀️🔦🏃‍♂️" },
    { q: "🛏️ Who is responsible for the pre-flight Safety Check of the MD-CRC?", a: "**MR5 Cabin Crew** 5️⃣👨‍✈️" },
    { q: "🔊 State the audio indication if the airflow into the LD-CRC is too low.", a: "A **buzzer will sound for 30 seconds** 🔔⏱️" },
    { q: "💡 Where in the cabin, can the emergency lights be manually activated from?", a: "The **Flight Attendant Panels (FAPs) at ML1 and UL1** by pressing the **EMER button to ON position** 🔦👆" },
    { q: "🌟 When will the slide raft and escape slide integral emergency lights illuminate?", a: "When the slide rafts and escape slides are **deployed** 🛶💡" },
    { q: "🧰 Where are the SRAKs located on board the A380?", a: "The SRAKs are located at **all stations except ML3 and MR3** 📍🧰" },
    { q: "🆘 When the EVAC CMD hard key at FAPs ML1 or UL1 is pressed, what is initiated?", a: "A **buzzer in the Flight Deck** with **no indications in the cabin** 🔔👨‍✈️🔇" },
    { q: "🦺 When should life jackets be inflated in a ditching situation?", a: "Life jackets should be inflated when **exiting the aircraft** 🛫🌊" },
    { q: "🚪 What are the secondary exits in case of ditching on the A380 aircraft?", a: "**None** ❌🚪" },
    { q: "🛝 Will the M1 slide extensions be deployed in a ditching situation?", a: "**No**. M1 slide extensions do not have a raft capability ❌🛶" },
  ];
  
  export default A380Questions;