const B777Questions = [
    { q: "Where is the Cabin System Control Panel (CSCP) located?", a: "The CSCP is located at **L1 station** above **Purser jump seat**." },
    { q: "Where are the smoke detectors located in the CRC?", a: "• One smoke detector is fitted in **each bunk**\n• One smoke detector is located in the **aisle between every pair of bunks**\n• **Two smoke detectors** are located in the **common area**" },
    { q: "State the location of the isolation valves on the B777-200 LR.", a: "• Above **L2 door**\n• On the **L4 CSP**" },
    { q: "What are the Cabin Crew actions when the command \"This is the Captain, Purser to the flight deck\" is heard in the cabin?", a: "• **Clear the cabin** of all service carts (if applicable)\n• **Return to their allocated stations**\n• **Review emergency SOPs** and await further communication from the Purser" },
    { q: "True or False? While administering oxygen, Cabin Crew must change the bottle when the pressure reaches 500 PSI (for post decompression crew use).", a: "**True**" },
    { q: "How would you make an announcement in Economy Class only?", a: "• **Remove** the handset from the cradle\n• **Check** for the dial tone\n• **Enter** the two digit code (**43**) for Economy Class (Zonal PA)\n• **Press and hold** PTT button" },
    { q: "How can a photoelectric smoke detector be silenced if it becomes active and triggers a false alarm during a power transfer?", a: "By pressing the flashing <span style=\"color: amber;\">**amber lavatory call light**</span> above the affected lavatory door." },
    { q: "If the cabin altitude exceeds 10,000 feet, what are the indications observed in the cabin?", a: "• Cabin lights come on **full bright** and **five HI chimes** sound\n• The **seat belt signs illuminate**\n• The **DECOMPRESSION pop-up window** appears on the CSCP and CACPs" },
    { q: "During a planned emergency ditching when will you inflate one chamber of the child's life jacket?", a: "Inflate **one chamber** during cabin preparation **away from passenger view**." },
    { q: "State the pre-flight check of the Infant/Extension Seat Belts.", a: "**Correct minimum quantity**.\nNote: Quantity in excess of the minimum requirement should not be off-loaded." },
    { q: "State the location of the EMER LIGHTS switches on the Aircraft.", a: "• The **Flight Deck overhead panel**\n• **L1 Crew Switch Panel**" },
    { q: "Where are the LR3 escape slides located on the B777-300?", a: "LR3 escape slides are integrated into the **belly fairing of the fuselage**." },
    { q: "True or False? LR3 doors on a B777-300 must be disarmed in case of ditching.", a: "**True**" },
    { q: "State the Cabin Crew commands to passengers when conducting a Precautionary Disembarkation using slides.", a: "\"**Open seat belts**\"\n\"**Leave everything**\"\n\"**This way**\" or\n\"**Go that way, go that way**\"" },
    { q: "When can the baby bassinet be used?", a: "May be used **during cruise**, while the **seat belt sign is switched off** and **no turbulence** is encountered." },
    { q: "During a land evacuation, what commands will the Cabin Crew use at an over-wing exit? (B777-300)", a: "\"**Step Down**, **Follow the Arrows**, **Jump and Slide**\"" },
    { q: "How can the cabin door status be checked on the B777?", a: "By selecting the '**CABIN DOOR STATUS**' page on the **CSCP** or **CACPs**." },
    { q: "What is the Safety Area of Responsibility of R1 on B777-300 (3 class)?", a: "Area of Responsibility:\n• **R1 station**\n• **R2 station to R1 station RHS**\n• **F/Class galley**" },
    { q: "What are the 3 levels of Turbulence?", a: "• **Light Turbulence**\n• **Moderate Turbulence**\n• **Severe Turbulence**" },
    { q: "State the purpose of the Infant Life Cot.", a: "It is used to **protect an infant in a ditching situation**." },
    { q: "Who is responsible for the pre-flight Safety Check of the CRC on B777-200 LR?", a: "**R3**" },
    { q: "Who is responsible for the pre-flight check of the 'A' position jump seat?", a: "The **station owner**" },
    { q: "What is the Flight Deck normal access code?", a: "**1** then **ENT**" },
    { q: "State the SOPs that Cabin Crew must follow, when a slow decompression is detected.", a: "• **Inform** the Flight Crew and other Cabin Crew\n• **Move passengers away** from the area. If not possible, passengers must fasten seat belts\n• If possible, use **pillows and blankets to cover the leak** and reduce the noise level\n• **Monitor the area regularly**" },
    { q: "State the purpose of the Sea Dye Marker.", a: "It releases a **fluorescent dye** to **attract attention** of the Search and Rescue services." },
    { q: "State the area of responsibility of L2 Cabin Crew on B777-300 (2 Class).", a: "• **L2 station**\n• **Row 15 to L2 station LHS**\n• **MID J/Class galley**" },
    { q: "State the safety and emergency equipment to be prepared by L4 Cabin Crew during cabin preparation for a planned emergency (Landing/Ditching) on a B777-300.", a: "• **1 SRAK**\n• **2 FAKS**\n• **1 Crew Life Jacket** (In case of Ditching)\n• **1 Emergency Vest**\n• **Water and Flashlight**" },
    { q: "During cabin door emergency operation, what should Cabin Crew check before evacuating passengers?", a: "Check that the related slide is **deployed and fully inflated**." },
    { q: "What are the Cabin Crew actions if only smoke is detected?", a: "If only smoke is present:\n• **Standby with a fire extinguisher**\n• **Investigate the source of smoke**" },
    { q: "When should Cabin Crew use their Emergency Vest?", a: "In the event of a **planned emergency landing** or **precautionary disembarkation**." },
  ];
  
  export default B777Questions;